// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NodeExecutor
{
    static class Vsix
    {
        public const string Id = "8c9a390f-5137-4f1d-b401-5cd079e6faa9";
        public const string Name = "Node Executor";
        public const string Description = @"Execute the current JavaScript file in the command prompt using Node.js";
        public const string Language = "en-US";
        public const string Version = "0.5";
        public const string Author = "Mads Kristensen";
        public const string Tags = "JavaScript, node";
    }
}
