// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NodeExecutor
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPrettierPackageString = "27196299-e92a-4dbd-b259-4c5b4baa7e31";
        public const string guidAutoloadString = "27196299-e92a-4dbd-b259-4c5b4baa7e31";
        public const string guidPrettierPackageCmdSetString = "ddfb1230-e89f-4847-881e-6ed29ecdbacf";
        public const string iconsString = "31947ebe-91b7-45f9-96cf-401bfc671aa2";
        public static Guid guidPrettierPackage = new Guid(guidPrettierPackageString);
        public static Guid guidAutoload = new Guid(guidAutoloadString);
        public static Guid guidPrettierPackageCmdSet = new Guid(guidPrettierPackageCmdSetString);
        public static Guid icons = new Guid(iconsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int PrettierCommandId = 0x0100;
        public const int ExecuteSolExp = 0x0200;
        public const int Logo = 0x0001;
    }
}
